name: cricupdate
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  image_picker: ^0.8.5+3
  dotted_line: ^3.2.2
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.3
  get: ^4.6.5
  flutter_svg: ^2.0.7
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  persistent_bottom_nav_bar: ^5.0.2
  csc_picker: ^0.2.7
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  cloud_firestore: ^4.8.2
  intl: ^0.17.0
  google_mobile_ads: ^3.0.0
  flick_video_player: ^0.5.0
  video_player: ^2.7.0
  easy_image_viewer: ^1.4.1
  youtube_player_flutter: ^8.1.2
  razorpay_web: ^1.3.6
  google_sign_in:
  http: ^0.13.3
  pull_to_refresh: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  fluttertoast: ^8.2.4
  loading_animation_widget: ^1.2.1
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.6
  device_info_plus: ^8.2.2
  permission_handler:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0


  flutter_lints: ^2.0.1


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon2.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

