// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9v2r_gGY52_3PBOw8PH1Ep9pcflnTzpw',
    appId: '1:846859021926:web:c0ffe0e707d2c4dfcdc7a7',
    messagingSenderId: '846859021926',
    projectId: 'cricupdate-3d464',
    authDomain: 'cricupdate-3d464.firebaseapp.com',
    storageBucket: 'cricupdate-3d464.appspot.com',
    measurementId: 'G-2R3P74PJG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwnGjcLFrmXI7XyTzXB_ivsj_WdO2M3gM',
    appId: '1:846859021926:android:410edc2e4c598de3cdc7a7',
    messagingSenderId: '846859021926',
    projectId: 'cricupdate-3d464',
    storageBucket: 'cricupdate-3d464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ivghLy9vgUm3txUekI53u9ybzJ9N3ao',
    appId: '1:846859021926:ios:d787c7af2be41893cdc7a7',
    messagingSenderId: '846859021926',
    projectId: 'cricupdate-3d464',
    storageBucket: 'cricupdate-3d464.appspot.com',
    iosClientId: '846859021926-au0fact3edivlttk9lfoqfi8tg97h7kk.apps.googleusercontent.com',
    iosBundleId: 'com.developers.cricupdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ivghLy9vgUm3txUekI53u9ybzJ9N3ao',
    appId: '1:846859021926:ios:41ced0a7f7066915cdc7a7',
    messagingSenderId: '846859021926',
    projectId: 'cricupdate-3d464',
    storageBucket: 'cricupdate-3d464.appspot.com',
    iosClientId: '846859021926-20b46hd4i6d17jhpp7l4lrggfsr3238r.apps.googleusercontent.com',
    iosBundleId: 'com.developers.cricupdate.RunnerTests',
  );
}
